# Generated by Django 5.0.6 on 2024-10-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='altitude',
        ),
    ]
